// <auto-generated/>
/* *******************************
Generated for type: OpenvrDataGetter.DevicePropertyUlong
Generated on: 3/12/2024 2:10:51 AM
Source assembly: Project-Obsidian, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
******************************* */

using System;
using ProtoFlux.Core;
using Elements.Core;
using FrooxEngine;
using FrooxEngine.ProtoFlux;
using OpenvrDataGetter;

namespace FrooxEngine.OpenvrDataGetter
{
    
    
    
    [Category("ProtoFlux/OpenvrDataGetter")]
    public  partial class DevicePropertyUlong : global::FrooxEngine.ProtoFlux.Runtimes.Execution.ValueFunctionNode<global::FrooxEngine.ProtoFlux.FrooxEngineContext, global::System.UInt64>
        
        
    {
        public override Type NodeType => typeof(global::OpenvrDataGetter.DevicePropertyUlong);

        

        
public global::OpenvrDataGetter.DevicePropertyUlong TypedNodeInstance { get; private set;}
public override INode NodeInstance => TypedNodeInstance;

public override N Instantiate<N>()
{
                if(TypedNodeInstance != null)
                    throw new InvalidOperationException("Node has already been instantiated");

                var node = new global::OpenvrDataGetter.DevicePropertyUlong();

                TypedNodeInstance = node;

                OnInstantiated();

                return node as N;
}

partial void OnInstantiated();

protected override void AssociateInstanceInternal(INode node)
{
    if(node is global::OpenvrDataGetter.DevicePropertyUlong typedNode)
    {
        TypedNodeInstance = typedNode;

        OnInstantiated();
    }
    else
        throw new ArgumentException("Node instance is not of type " + typeof(global::OpenvrDataGetter.DevicePropertyUlong));
}

public override void ClearInstance() => TypedNodeInstance = null;


        
        
        

        public override int NodeInputCount => base.NodeInputCount + 2;
        

        
        

        
        

        
        

        

        
        

             protected override ISyncRef GetInputInternal(ref int index)
        {
            var @base = base.GetInputInternal(ref index);

            if(@base != null)
                return @base;

            switch(index)
            {
                case 0: return Index;
case 1: return prop;

                default:
                    index -= 2;
                    return null;
            };
        }

        
        
        

        

        
        
        
        

        
        

        

		public readonly SyncRef<global::FrooxEngine.ProtoFlux.INodeValueOutput<global::System.UInt32>> Index;
		public readonly SyncRef<global::FrooxEngine.ProtoFlux.INodeValueOutput<global::OpenvrDataGetter.UlongDeviceProperty>> prop;

    }
}
