// <auto-generated/>
/* *******************************
Generated for type: OpenvrDataGetter.Nodes.DevicePropertyArray`2
Generated on: 3/12/2024 2:10:51 AM
Source assembly: Project-Obsidian, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
******************************* */

using System;
using ProtoFlux.Core;
using Elements.Core;
using FrooxEngine;
using FrooxEngine.ProtoFlux;
using OpenvrDataGetter.Nodes;

namespace FrooxEngine.OpenvrDataGetter.Nodes
{
    
    [GenericTypes(GenericTypesAttribute.Group.EnginePrimitivesAndEnums)]
    
    [Category("ProtoFlux/Runtimes/Execution/Nodes/OpenvrDataG    [Category(new string[] { \"ProtoFlux/Runtimes/Execution/Nodes/Obsidian/OpenvrDataGetter\" })]\r\netter")]
    public abstract partial class DevicePropertyArray<T, P> : global::FrooxEngine.OpenvrDataGetter.Nodes.DevicePropertyArrayBase<T, P, T>
        
         where T : unmanaged where P : unmanaged, global::System.Enum
    {
        public override Type NodeType => typeof(global::OpenvrDataGetter.Nodes.DevicePropertyArray<T, P>);

        

        

        
        
        

        
        

        
        

        
        

        
        

        

        
        

        
        
        
        

        

        
        
        
        

        
        

        


    }
}
