//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net;
using System.Reflection;
using Newtonsoft.Json.Linq;

using Elements.Core;

[assembly: System.Reflection.AssemblyCompanyAttribute("Project-Obsidian")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright ©  2024")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+09f5737d6929d0dd439b34f23667465a4105bc78")]
[assembly: System.Reflection.AssemblyProductAttribute("Project-Obsidian")]
[assembly: System.Reflection.AssemblyTitleAttribute("Project-Obsidian")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

//Mark as DataModelAssembly for the Plugin loading system to load this assembly
[assembly: DataModelAssembly(DataModelAssemblyType.Core)]

[assembly: ExternalDataModelType(typeof(Valve.VR.Imu_OffScaleFlags))]
[assembly: ExternalDataModelType(typeof(HttpStatusCode))]
[assembly: ExternalDataModelType(typeof(JObject))]
[assembly: ExternalDataModelType(typeof(JToken))]
[assembly: ExternalDataModelType(typeof(JArray))]